from __future__ import annotations

from typing import Any, Dict, Iterable, Protocol


class OutputRenderer(Protocol):
    def banner(self, text: str) -> None: ...

    def echo(self, text: str) -> None: ...

    def print_list(self, rows: Iterable[Dict[str, str]], *, quiet: bool = False) -> None: ...

    def print_summary(self, summary: Dict[str, Any]) -> None: ...

    def print_events(self, events: Iterable[Dict[str, Any]]) -> None: ...

    def json(self, data: Any) -> None: ...
