from __future__ import annotations

from typing import TYPE_CHECKING, Any, Dict, Iterable, Protocol

if TYPE_CHECKING:
    from ..view_models import EpisodeDashboardVM
    from ..content.home import HomeScreen
    from ..content.help import HelpScreen


class OutputRenderer(Protocol):
    def banner(self, text: str) -> None: ...

    def echo(self, text: str) -> None: ...

    def print_list(self, rows: Iterable[Dict[str, str]], *, quiet: bool = False) -> None: ...

    def print_summary(self, summary: Dict[str, Any]) -> None: ...

    def print_events(self, events: Iterable[Dict[str, Any]]) -> None: ...

    def json(self, data: Any) -> None: ...

    def print_viewer(self, view: Any, *, grep: str | None = None) -> None: ...

    def print_ps(self, rows: Iterable[Dict[str, str]], *, quiet: bool = False) -> None: ...

    def print_home(self, screen: Any) -> None: ...

    def print_help(self, screen: Any) -> None: ...

    def print_command_help(self, text: str, *, title: str | None = None) -> None: ...
